
if [[ ! -e ${INFILE}.virus_list.fastq ]]; then

echo grepping virus in ${INFILE} >> ${INDIR}/log



### input: INFILE has extension _clean.fq_output.taxo

dir=`dirname ${INFILE}`
base=`basename ${INFILE} _output.taxo` ### base will have extension "_clean.fq"


grep Virus ${INFILE} | cut -f 2 > ${INFILE}.virus_list
perl /data3/projects/cisbi-0136/Tools/get_fastq_from_name_seq.pl ${INFILE}.virus_list ${dir}/${base} ${INFILE}.virus_list.fastq

else
echo ${INFILE}.virus_list.fastq already exists
fi;
